version: '3.8'

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/auth
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth
      MYSQL_PASSWORD: password



